title: Great Web Agency
email: safayarma1@gmail.com
description: "Great Web Agency offers high impact yet affordable web development services.
From web design, to targeted SEO, and to custom web applications."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://safayarma.github.io/my-jekyll-site/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
  markdown: kramdown


permalink: none
comments: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Safa M-A"
      category: "jekyll"
